#!/usr/bin/env bash
set -euo pipefail

readonly PERSONA_HOSTNAME="prod-app-server-01"
readonly COWRIE_HOME="/home/cowrie/cowrie"
readonly FS_SOURCE="${COWRIE_HOME}/var/lib/cowrie/fs-source"
readonly KEY_MARKER="/var/lib/honeytrace/ssh-host-keys-regenerated"

if [[ "${EUID}" -ne 0 ]]; then
  echo "This script must run as root." >&2
  exit 1
fi

echo "Setting host hostname to ${PERSONA_HOSTNAME}..."
hostnamectl set-hostname "${PERSONA_HOSTNAME}"

echo "Writing the host MOTD and Cowrie's fake Ubuntu-style MOTD..."
install -d -m 0755 /var/lib/honeytrace
cat > /etc/motd <<'EOF'
Welcome to Ubuntu 22.04.5 LTS (GNU/Linux 5.15.0-105-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

System information as of \l
EOF

install -d -o cowrie -g cowrie -m 0750 "${FS_SOURCE}/etc"
cp /etc/motd "${FS_SOURCE}/etc/motd"
printf '%s\n' "${PERSONA_HOSTNAME}" > "${FS_SOURCE}/etc/hostname"
chown cowrie:cowrie "${FS_SOURCE}/etc/motd" "${FS_SOURCE}/etc/hostname"

if [[ ! -e "${KEY_MARKER}" ]]; then
  echo "Regenerating OpenSSH host keys..."
  rm -f /etc/ssh/ssh_host_*
  ssh-keygen -A
  touch "${KEY_MARKER}"
else
  echo "OpenSSH host keys were already regenerated by this bootstrap."
fi

echo "Stealth persona configured."
